// <auto-generated />
namespace twActivitiest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addAllDatabase5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addAllDatabase5));
        
        string IMigrationMetadata.Id
        {
            get { return "201911290251563_addAllDatabase5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
